[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "geopandas>=1.1.1",
    "networkx>=3.5",
    "osmnx>=2.0.5",
    "shapely>=2.1.1",
]
